//! VEFAS SP1 methods crate
//!
//! This crate contains the compiled SP1 guest program ELF generated by the build script.
//! The guest program verifies VEFAS canonical bundles inside the SP1 zkVM.

use sp1_sdk::include_elf;

/// The ELF we want to execute inside the SP1 zkVM.
/// This contains the compiled VEFAS verification program.
pub const VEFAS_SP1_ELF: &[u8] = include_elf!("vefas-sp1-program");
