//! Unified RISC0 zkTLS implementation
//!
//! This crate provides a complete RISC0 implementation of zkTLS verification,
//! following the official RISC0 examples pattern with both host and guest code
//! in a single crate.

use zktls_zkvm::types::*;
use risc0_zkvm::{default_prover, ExecutorEnv, Receipt, default_executor};
use std::time::Instant;

// Include the compiled RISC0 guest program ELF and method ID
// These are generated by the methods crate build script
use zktls_risc0_methods::{ZKTL_VERIFY_ELF, ZKTL_VERIFY_ID};

/// RISC0 zkTLS prover
///
/// This struct handles proof generation and verification for RISC0 zkVM
/// executions of the zkTLS verification program.
///
/// Implementation follows the official RISC0 ECDSA P256 example patterns:
/// - Uses ExecutorEnv::builder() for environment setup
/// - Uses default_prover() for proof generation
/// - Uses Receipt::verify() for proof verification
/// - Uses env::read() and env::commit() in guest program
pub struct RISC0ZkTlsProver;

impl RISC0ZkTlsProver {
    /// Create a new RISC0 zkTLS prover
    ///
    /// Uses the correct RISC0 SDK API pattern from official examples.
    pub fn new() -> Self {
        Self
    }

    /// Generate a proof for the given input
    ///
    /// Implementation follows the official RISC0 examples pattern:
    /// 1. Create ExecutorEnv and write input
    /// 2. Use default_prover() to generate proof
    /// 3. Extract claim from journal
    /// 4. Return structured proof wrapper
    pub fn generate_proof(&self, input: &ZkTlsInput) -> Result<RISC0ProofWrapper, ZkTlsError> {
        let start_time = Instant::now();

        // Create executor environment with input
        let env = ExecutorEnv::builder()
            .write(input)
            .map_err(|e| ZkTlsError::InvalidInput(format!("Failed to write input to executor: {}", e)))?
            .build()
            .map_err(|e| ZkTlsError::ExecutionError(format!("Failed to build executor environment: {}", e)))?;

        // Generate proof using default prover (following RISC0 hello-world example pattern)
        let proof_start = Instant::now();
        let prover = default_prover();
        let receipt = prover
            .prove(env, ZKTL_VERIFY_ELF)
            .map_err(|e| ZkTlsError::ExecutionError(format!("RISC0 proof generation failed: {}", e)))?
            .receipt;

        let proof_time = proof_start.elapsed();

        // Extract claim from journal (following RISC0 ECDSA pattern)
        let claim = self.extract_claim_from_receipt(&receipt, input)?;

        // Get real execution metadata from receipt
        let execution_metadata = ExecutionMetadata {
            cycles: self.get_execution_cycles_from_receipt(&receipt),
            memory_usage: self.get_memory_usage_from_receipt(&receipt),
            execution_time_ms: start_time.elapsed().as_millis() as u64,
            platform: "risc0".to_string(),
            proof_time_ms: proof_time.as_millis() as u64,
        };

        Ok(RISC0ProofWrapper {
            receipt: bincode::serialize(&receipt)
                .map_err(|e| ZkTlsError::SerializationError(format!("Failed to serialize receipt: {}", e)))?,
            claim,
            execution_metadata,
        })
    }

    /// Verify a proof
    ///
    /// Implementation follows the official RISC0 examples pattern:
    /// 1. Deserialize receipt
    /// 2. Use Receipt::verify() for verification
    /// 3. Return the verified claim
    pub fn verify_proof(&self, proof: &RISC0ProofWrapper) -> Result<ZkTlsProofClaim, ZkTlsError> {
        // Decode receipt from bytes
        let receipt: Receipt = bincode::deserialize(&proof.receipt)
            .map_err(|e| ZkTlsError::SerializationError(format!("Failed to decode receipt: {}", e)))?;

        // Verify receipt using correct RISC0 SDK API (following RISC0 ECDSA pattern)
        receipt
            .verify(ZKTL_VERIFY_ID)
            .map_err(|e| ZkTlsError::ExecutionError(format!("RISC0 proof verification failed: {}", e)))?;

        Ok(proof.claim.clone())
    }

    /// Execute without generating a full proof (for testing/debugging)
    ///
    /// This method runs the guest program and returns the result without
    /// generating a cryptographic proof, useful for testing and debugging.
    pub fn execute(&self, input: &ZkTlsInput) -> Result<ZkTlsVerificationResult, ZkTlsError> {
        let start_time = Instant::now();

        let env = ExecutorEnv::builder()
            .write(input)
            .map_err(|e| ZkTlsError::InvalidInput(format!("Failed to write input to executor: {}", e)))?
            .build()
            .map_err(|e| ZkTlsError::ExecutionError(format!("Failed to build executor environment: {}", e)))?;

        let session_info = default_executor()
            .execute(env, ZKTL_VERIFY_ELF)
            .map_err(|e| ZkTlsError::ExecutionError(format!("RISC0 execution failed: {}", e)))?;

        let claim: ZkTlsProofClaim = session_info.journal.decode()
            .map_err(|e| ZkTlsError::SerializationError(format!("Failed to decode journal after execution: {}", e)))?;

        let execution_metadata = ExecutionMetadata {
            cycles: session_info.get_metadata().map_or(0, |m| m.total_cycles),
            memory_usage: session_info.journal.bytes.len() as u64, // Estimate memory usage from journal size
            execution_time_ms: start_time.elapsed().as_millis() as u64,
            platform: "risc0".to_string(),
            proof_time_ms: 0, // No proof generated in execute mode
        };

        Ok(ZkTlsVerificationResult {
            success: true,
            claim: Some(claim),
            error: None,
            execution_metadata,
        })
    }

    /// Extract claim from RISC0 receipt journal
    fn extract_claim_from_receipt(&self, receipt: &Receipt, _input: &ZkTlsInput) -> Result<ZkTlsProofClaim, ZkTlsError> {
        // Read the complete ZkTlsProofClaim that was committed by the guest program
        // The guest program commits the entire claim as a structured object
        let claim: ZkTlsProofClaim = receipt.journal.decode()
            .map_err(|e| ZkTlsError::SerializationError(format!("Failed to decode journal: {}", e)))?;
        Ok(claim)
    }

    /// Get execution cycles from receipt
    ///
    /// Extracts execution cycles from the RISC0 receipt.
    fn get_execution_cycles_from_receipt(&self, receipt: &Receipt) -> u64 {
        // RISC0 receipts contain execution metadata in the `total_cycles` field
        receipt.get_metadata().map_or(0, |m| m.total_cycles)
    }

    /// Get memory usage from receipt
    ///
    /// Estimates memory usage based on receipt characteristics.
    fn get_memory_usage_from_receipt(&self, receipt: &Receipt) -> u64 {
        // RISC0 receipts contain execution metadata in the `total_memory` field
        // For now, we'll use a placeholder or estimate based on journal size
        let journal_size = receipt.journal.bytes.len() as u64;
        let seal_overhead = receipt.inner.flat().len() as u64; // Estimate seal size
        // A rough estimate: base memory + journal size + seal size
        2 * 1024 * 1024 + journal_size + seal_overhead // 2MB base + journal size + seal size
    }
}

/// RISC0 proof wrapper
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct RISC0ProofWrapper {
    /// The actual RISC0 receipt serialized as bytes
    pub receipt: Vec<u8>,
    /// The proof claim extracted from journal
    pub claim: ZkTlsProofClaim,
    /// Execution metadata from proof generation
    pub execution_metadata: ExecutionMetadata,
}

impl RISC0ZkTlsProver {
    /// Generate proof and verify it in one operation
    ///
    /// This is a convenience method that generates a proof and immediately verifies it,
    /// returning a structured verification result.
    pub fn generate_and_verify_proof(&self, input: &ZkTlsInput) -> Result<ZkTlsVerificationResult, ZkTlsError> {
        match self.generate_proof(input) {
            Ok(proof) => {
                match self.verify_proof(&proof) {
                    Ok(claim) => Ok(ZkTlsVerificationResult {
                        success: true,
                        claim: Some(claim),
                        error: None,
                        execution_metadata: proof.execution_metadata,
                    }),
                    Err(e) => Ok(ZkTlsVerificationResult {
                        success: false,
                        claim: None,
                        error: Some(e.to_string()),
                        execution_metadata: proof.execution_metadata,
                    }),
                }
            }
            Err(e) => Ok(ZkTlsVerificationResult {
                success: false,
                claim: None,
                error: Some(e.to_string()),
                execution_metadata: ExecutionMetadata {
                    cycles: 0,
                    memory_usage: 0,
                    execution_time_ms: 0,
                    platform: "risc0".to_string(),
                    proof_time_ms: 0,
                },
            }),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::vec;

    /// Helper function to create a mock ZkTlsInput for testing
    fn create_mock_zktls_input() -> ZkTlsInput {
        ZkTlsInput {
            domain: "example.com".to_string(),
            handshake_transcript: vec![0x01, 0x02, 0x03],
            certificates: vec![vec![0x04, 0x05], vec![0x06, 0x07]],
            http_request: vec![0x08, 0x09],
            http_response: vec![0x0a, 0x0b],
            timestamp: 1678886400, // Example timestamp
            metadata: ZkTlsMetadata {
                tls_version: "1.3".to_string(),
                cipher_suite: "TLS_AES_128_GCM_SHA256".to_string(),
                client_random: [0u8; 32],
                server_random: [0u8; 32],
                session_id: None,
                extensions: Vec::new(),
            },
        }
    }

    #[test]
    fn test_risc0_prover_initialization() {
        // Initialize the RISC0 prover
        let _prover = RISC0ZkTlsProver::new();

        // Assert that the prover was created successfully (no panic)
        assert!(true, "RISC0ZkTlsProver should initialize without panicking");
    }

    #[test]
    fn test_risc0_proof_generation_mock_input() {
        // Initialize the RISC0 prover
        let prover = RISC0ZkTlsProver::new();

        // Create a mock input
        let input = create_mock_zktls_input();

        // Generate the proof
        let result = prover.generate_proof(&input);

        // Assert that proof generation was successful
        assert!(result.is_ok(), "Proof generation failed: {:?}", result.err());
        let proof_wrapper = result.unwrap();

        // Assert that the claim is present and has expected values
        assert!(proof_wrapper.claim.domain == input.domain);
        assert!(proof_wrapper.execution_metadata.platform == "risc0");
    }

    #[test]
    fn test_risc0_proof_verification_mock_input() {
        // Initialize the RISC0 prover
        let prover = RISC0ZkTlsProver::new();

        // Create a mock input
        let input = create_mock_zktls_input();

        // Generate the proof
        let proof_wrapper = prover
            .generate_proof(&input)
            .expect("Proof generation failed");

        // Verify the generated proof
        let verification_result = prover.verify_proof(&proof_wrapper);

        // Assert that proof verification was successful
        assert!(
            verification_result.is_ok(),
            "Proof verification failed: {:?}",
            verification_result.err()
        );
        let verified_claim = verification_result.unwrap();

        // Assert that the verified claim matches the generated claim
        assert_eq!(proof_wrapper.claim.domain, verified_claim.domain);
        assert_eq!(
            proof_wrapper.claim.request_commitment,
            verified_claim.request_commitment
        );
        assert_eq!(
            proof_wrapper.claim.response_commitment,
            verified_claim.response_commitment
        );
        assert_eq!(proof_wrapper.claim.status_code, verified_claim.status_code);
    }

    #[test]
    fn test_risc0_proof_serialization_deserialization() {
        // Initialize the RISC0 prover
        let prover = RISC0ZkTlsProver::new();

        // Create a mock input
        let input = create_mock_zktls_input();

        // Generate a proof
        let proof_wrapper = prover
            .generate_proof(&input)
            .expect("Proof generation failed");

        // Serialize the proof wrapper
        let serialized_proof =
            bincode::serialize(&proof_wrapper).expect("Failed to serialize proof wrapper");

        // Deserialize the proof wrapper
        let deserialized_proof: RISC0ProofWrapper =
            bincode::deserialize(&serialized_proof)
                .expect("Failed to deserialize proof wrapper");

        // Assert that the deserialized proof matches the original
        assert_eq!(proof_wrapper.claim.domain, deserialized_proof.claim.domain);
        assert_eq!(
            proof_wrapper.execution_metadata.platform,
            deserialized_proof.execution_metadata.platform
        );
        assert_eq!(proof_wrapper.receipt.len(), deserialized_proof.receipt.len());

        // Verify the deserialized proof
        let verification_result = prover.verify_proof(&deserialized_proof);
        assert!(
            verification_result.is_ok(),
            "Deserialized proof verification failed: {:?}",
            verification_result.err()
        );
    }
}
