//! RISC0 methods crate for zkTLS verification
//!
//! This crate contains the compiled RISC0 guest program ELF and method ID
//! generated by the build script.

include!(concat!(env!("OUT_DIR"), "/methods.rs"));
