//! SP1 methods crate for zkTLS verification
//!
//! This crate contains the compiled SP1 guest program ELF generated by the build script.

use sp1_sdk::include_elf;

/// The ELF we want to execute inside the SP1 zkVM.
pub const ELF: &[u8] = include_elf!("zktls-program");
