//! VEFAS RISC0 methods crate
//!
//! This crate contains the compiled RISC0 guest program ELF and method ID
//! generated by the build script. The guest program verifies VEFAS canonical bundles
//! inside the RISC0 zkVM.

include!(concat!(env!("OUT_DIR"), "/methods.rs"));
